### PR TITLE
Add tests for BytesConverseUtil

### PR DESCRIPTION
**Pull request by freddytuxworth**
Hi,
This PR adds JUnit as a dependency to enable unit testing of the project. It also adds tests for `org.nesc.ecbd.util.BytesConverseUtil`, which were written using [Diffblue Cover](https://www.diffblue.com/opensource). Hopefully these should help detect any regressions caused by future code changes in this class.  

If you would like to use unit testing in this project, please let me know - I would be more than happy to write more tests for other classes.

### CODE REVIEW

**Review by petersear — APPROVED** [review]
In the PR text, I'd suggest changing `Junit` to `JUnit` as it is normally written.

**Review by JohnLBergqvist — CHANGES_REQUESTED** [review]
I would check you've spelt `tests` correctly in that 2nd commit message...

**Review by JohnLBergqvist — CHANGES_REQUESTED** [review]
Ensure the commit message is correct.

**Review by JohnLBergqvist — APPROVED** [review]

**Review by JohnLBergqvist — CHANGES_REQUESTED** [review]
You need to add in the 2nd line of the commit message...

**Review by JohnLBergqvist — APPROVED** [review]

**Pull request closed without merging**
